### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [pshushereba/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by pshushereba** [comment]
I've added the following to my application.html.erb file:

```
<meta name="viewport" content="width=device-width, initial-scale=1">
```

I've placed in my head tag, based on the directions from Bootstrap documentation.

http://getbootstrap.com/css/

I've looked at the app on the minimized window (our sample "mobile" device). I've checked it with and without the code, but I'm not seeing the difference, most likely to my being new at this. Was this enough to solve the problem that you encountered?

**Comment by kenmazaika** [comment]
Yup!  That line of code will do it.  Make sure to push your commit your code and push up to GitHub and Heroku too! :+1:
